# fly.toml app configuration file generated for jenkins-autumn-waterfall-572 on 2025-04-17T13:13:38+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jenkins-aged-wildflower-9382'
primary_region = 'sjc'

[build]

[[mounts]]
  source = "jenkins_home"
  destination = "/var/jenkins_home"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
